# Migracja tworzy tabelę łączącą lokalnych użytkowników ze zweryfikowanymi kontami Google.
# Generated by Django 6.0.5 on 2026-06-07 10:43

import django.db.models.deletion  # Moduł zawiera zachowanie CASCADE dla relacji z użytkownikiem.
from django.conf import settings  # Ustawienia wskazują aktualny model użytkownika projektu.
from django.db import migrations, models  # Klasy opisują operacje i pola tworzonej tabeli.


class Migration(migrations.Migration):
    """Pierwsza migracja aplikacji accounts."""

    initial = True  # Django wie, że od tego pliku zaczyna się historia schematu aplikacji.

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Tabela użytkowników musi istnieć wcześniej.
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',  # Nazwa modelu staje się podstawą nazwy tabeli w bazie.
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Klucz główny rekordu.
                ('subject', models.CharField(help_text='Stabilny identyfikator użytkownika z pola sub tokenu Google.', max_length=255, unique=True)),  # Unikalne pole sub.
                ('email', models.EmailField(help_text='Zweryfikowany adres e-mail otrzymany w tokenie Google.', max_length=254)),  # Kopia zweryfikowanego e-maila.
                ('picture_url', models.URLField(blank=True, help_text='Opcjonalny adres zdjęcia profilowego użytkownika.', max_length=500)),  # Opcjonalny avatar.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Moment utworzenia powiązania.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Moment ostatniej aktualizacji profilu.
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_account', to=settings.AUTH_USER_MODEL)),  # Właściciel konta.
            ],
            options={
                'verbose_name': 'konto Google',  # Polska nazwa w panelu administracyjnym.
                'verbose_name_plural': 'konta Google',  # Polska nazwa listy w panelu administracyjnym.
                'ordering': ('-created_at',),  # Najnowsze powiązania są pobierane jako pierwsze.
            },
        ),
    ]
