"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta  # timedelta pozwala czytelnie określić czas ważności tokenów JWT.
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-gmncs(oht5_**-a$f=wvuup&g50sb2up@ttp7##4(@%3*m-rj-',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'accounts',
    'core',
    'observations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

POSTGRES_HOST = os.getenv('POSTGRES_HOST')

if POSTGRES_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'mzm_db'),
            'USER': os.getenv('POSTGRES_USER', 'mzm_user'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'mzm_password'),
            'HOST': POSTGRES_HOST,
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': 60,  # Krótkie utrzymanie połączeń ogranicza narzut w API i workerze.
            'CONN_HEALTH_CHECKS': True,  # Django sprawdza trwałe połączenie przed jego ponownym użyciem.
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('SQLITE_DATABASE_PATH', BASE_DIR / 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [  # Lista adresów frontendu, którym backend pozwala wysyłać requesty z przeglądarki.
    origin.strip()  # Czyścimy spacje, żeby zmienne środowiskowe były odporne na formatowanie.
    for origin in os.getenv(
        'CORS_ALLOWED_ORIGINS',  # Zmienna pozwala nadpisać listę originów bez edycji kodu.
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174',
    ).split(',')  # W env trzymamy listę jako tekst rozdzielony przecinkami.
    if origin.strip()  # Pomijamy puste wpisy, gdy ktoś doda przypadkowy przecinek.
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Client ID jest publicznym identyfikatorem aplikacji i służy do sprawdzania pola aud tokenu Google.
GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID', '')

# Access token jest krótki, a refresh token pozwala utrzymać sesję bez częstego logowania przez Google.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Krótki czas ogranicza skutki przejęcia access tokenu.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Użytkownik pozostaje zalogowany maksymalnie przez tydzień.
    'ROTATE_REFRESH_TOKENS': False,  # Na tym etapie zachowujemy prosty mechanizm jednego refresh tokenu.
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'NieZmoknij API',
    'DESCRIPTION': 'API do agregowania danych pogodowych, sejsmicznych i wulkanicznych.',
    'VERSION': '0.1.0',
}

REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# Django używa Redisa jako współdzielonego cache dla wszystkich procesów backendu i przyszłych workerów Celery.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',  # Wbudowany backend korzysta z pakietu redis-py.
        'LOCATION': REDIS_URL,  # Ten sam adres działa lokalnie i w sieci Docker Compose.
        'KEY_PREFIX': 'niezmoknij',  # Prefiks oddziela klucze projektu od innych aplikacji w tej samej instancji.
        'TIMEOUT': 300,  # Domyślny TTL wynosi 5 minut, jeśli widok nie poda własnej wartości.
        'OPTIONS': {
            'socket_connect_timeout': 2,  # Backend szybko zgłosi problem, gdy Redis jest niedostępny.
            'socket_timeout': 2,  # Operacja cache nie może blokować requestu przez długi czas.
        },
    }
}

# Aktualna pogoda zapisanej lokalizacji jest świeża wystarczająco długo przez 15 minut.
LOCATION_WEATHER_CACHE_TTL = int(os.getenv('LOCATION_WEATHER_CACHE_TTL', '900'))

# Redis pełni dwie odrębne role: cache Django oraz broker komunikatów dla Celery.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', REDIS_URL)  # Domyślnie worker używa tej samej instancji Redisa.
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', REDIS_URL)  # Wynik zadania pomaga w diagnostyce kolejki.
CELERY_TASK_TRACK_STARTED = True  # Stan STARTED odróżnia zadanie oczekujące od faktycznie wykonywanego.
CELERY_TASK_TIME_LIMIT = 5 * 60  # Twardy limit pięciu minut chroni worker przed zawieszonym API zewnętrznym.
CELERY_TASK_SOFT_TIME_LIMIT = 4 * 60  # Miękki limit pozwala Celery zakończyć zadanie i zapisać błąd.
CELERY_TIMEZONE = 'UTC'  # Harmonogram używa tej samej strefy co baza Django.
CELERY_BEAT_SCHEDULE = {  # Scheduler cyklicznie zasila bazę bez requestu użytkownika.
    'sync-earthquakes-every-five-minutes': {
        'task': 'observations.sync_earthquakes',  # Zdarzenia sejsmiczne zmieniają się dynamicznie.
        'schedule': 5 * 60,  # Pięć minut odpowiada TTL warstwy sejsmicznej.
    },
    'sync-volcano-catalog-every-day': {
        'task': 'observations.sync_volcanic_events',  # Pełny katalog Smithsonian zmienia się znacznie wolniej niż pogoda.
        'schedule': 24 * 60 * 60,  # Jedna synchronizacja dziennie ogranicza transfer dużej historii erupcji.
    },
    'sync-saved-weather-every-fifteen-minutes': {
        'task': 'observations.sync_saved_location_weather',  # Historia pogody dotyczy zapisanych lokalizacji.
        'schedule': 15 * 60,  # Harmonogram jest zgodny z TTL cache pogody.
    },
}
