# Plik migracji jest generowany przez Django; komentarz wyjaśnia, że opisuje pierwszy schemat tabel.
# Generated by Django 6.0.5 on 2026-05-30 17:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('magnitude', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('depth_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('place', models.CharField(blank=True, max_length=255)),
                ('event_time', models.DateTimeField()),
                ('source', models.CharField(max_length=80)),
                ('detail_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['-event_time'], name='observation_event_t_6cbdec_idx'), models.Index(fields=['magnitude'], name='observation_magnitu_019412_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('WEATHER_SYNC', 'Weather sync'), ('EARTHQUAKE_SYNC', 'Earthquake sync'), ('VOLCANO_SYNC', 'Volcano sync')], max_length=40)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_fetched', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_type', '-started_at'], name='observation_job_typ_d37087_idx'), models.Index(fields=['status'], name='observation_status_ef4851_idx')],
            },
        ),
        migrations.CreateModel(
            name='VolcanicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('volcano_name', models.CharField(blank=True, max_length=160)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('region', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('event_time', models.DateTimeField()),
                ('source', models.CharField(max_length=80)),
                ('detail_url', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['-event_time'], name='observation_event_t_0bff51_idx'), models.Index(fields=['region'], name='observation_region_7834f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pressure', models.PositiveSmallIntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(max_length=80)),
                ('measured_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='observations.savedlocation')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='savedlocation',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'latitude', 'longitude'), name='unique_saved_location_per_user'),
        ),
        migrations.AddIndex(
            model_name='weathersnapshot',
            index=models.Index(fields=['location', '-measured_at'], name='observation_locatio_22c696_idx'),
        ),
    ]
