# Migracja rozszerza historię pogody i wzmacnia regułę unikalności zapisanych punktów.
# Generated by Django 6.0.5 on 2026-06-12 15:53

import django.core.validators  # Walidatory pilnują zakresu procentowego zachmurzenia.
from django.conf import settings  # Ustawienia wskazują aktywny model użytkownika.
from django.db import migrations, models  # Klasy opisują zmiany wykonywane na schemacie bazy.


class Migration(migrations.Migration):
    """Druga migracja modułu obserwacji środowiskowych."""

    dependencies = [
        ('observations', '0001_initial'),  # Najpierw musi istnieć bazowy schemat modeli obserwacyjnych.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Ograniczenie lokalizacji zależy od tabeli użytkowników.
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='savedlocation',  # Zmieniamy regułę dotyczącą tabeli zapisanych lokalizacji.
            name='unique_saved_location_per_user',  # Stara reguła uwzględniała również nazwę punktu.
        ),
        migrations.AddField(
            model_name='weathersnapshot',  # Pole trafia do tabeli historycznych pomiarów.
            name='cloud_cover',  # Zachmurzenie przechowujemy jako opcjonalny procent.
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='weathersnapshot',  # Kod WMO należy do tego samego pomiaru co temperatura i wiatr.
            name='weather_code',  # Pole pozwala odtworzyć opis warunków.
            field=models.PositiveSmallIntegerField(blank=True, null=True),  # Brak kodu pozostaje dozwolony.
        ),
        migrations.AddConstraint(
            model_name='savedlocation',  # Nowa reguła działa na tabeli lokalizacji.
            constraint=models.UniqueConstraint(fields=('user', 'latitude', 'longitude'), name='unique_saved_coordinates_per_user'),
        ),
    ]
