# Migracja zapobiega wielokrotnemu zapisaniu tego samego pomiaru przez request HTTP i worker Celery.
# Generated by Django 6.0.5 on 2026-06-12 18:42

from django.db import migrations, models  # Klasy opisują zmianę ograniczeń schematu.


class Migration(migrations.Migration):
    """Dodaje bazodanową regułę unikalności snapshotu pogodowego."""

    dependencies = [
        ('observations', '0002_remove_savedlocation_unique_saved_location_per_user_and_more'),  # Najpierw muszą istnieć pola źródła i czasu.
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weathersnapshot',  # Ograniczenie dotyczy tabeli historycznych pomiarów.
            constraint=models.UniqueConstraint(
                fields=('location', 'source', 'measured_at'),  # Trzy pola jednoznacznie opisują pomiar źródłowy punktu.
                name='unique_weather_measurement_per_location',  # Nazwa jest czytelna w PostgreSQL i komunikatach błędów.
            ),
        ),
    ]
