# Generated by Django 6.0.5 on 2026-06-12 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_weathersnapshot_unique_weather_measurement_per_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volcanicevent',
            options={'ordering': ['volcano_name']},
        ),
        migrations.RemoveIndex(
            model_name='volcanicevent',
            name='observation_event_t_0bff51_idx',
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='elevation_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='evidence_category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='geologic_epoch',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='last_eruption_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='max_vei',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='photo_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='rock_type',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='tectonic_setting',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='vei',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='volcanicevent',
            name='volcano_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='volcanicevent',
            name='detail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='volcanicevent',
            name='event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volcanicevent',
            name='region',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddIndex(
            model_name='volcanicevent',
            index=models.Index(fields=['volcano_name'], name='observation_volcano_9b1906_idx'),
        ),
        migrations.AddIndex(
            model_name='volcanicevent',
            index=models.Index(fields=['country'], name='observation_country_347d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='volcanicevent',
            index=models.Index(fields=['max_vei'], name='observation_max_vei_ea5e49_idx'),
        ),
    ]
